### PR TITLE
Disable break-drive fault checks

### PR DESCRIPTION
**Pull request by forrest-rm**

### CODE REVIEW

**Review by johnsonTyler0511 — APPROVED** [review]

**Comment by johnsonTyler0511** [comment]
Does this fail to startup on the first time and then work the second time?

**Comment by forrest-rm** [comment]
> Does this fail to startup on the first time and then work the second time?

It did the first time. It seems that the checks remain disabled after we bring down our ROS controllers, so I'll need to test a few times with power cycling the Kinova controller.

**Review by MarqRazz — COMMENTED** [review]
Is this something that needs to be run every time the robot starts? If not I think it would be better to have a separate script that you can run to do the one time disabling.

**Comment by forrest-rm** [comment]
> Is this something that needs to be run every time the robot starts? If not I think it would be better to have a separate script that you can run to do the one time disabling.

We are seeing the break-line faults when bringup the robot arm, so we need to disable the faults before enabling the actuators. It might be possible to move this to a separate file, but then we would need someway for that file to be called. This is probably the most robust solution for now.

**Comment by MarqRazz** [comment]
Right, but it is also dangerous to ignore faults like this which is why I was suggesting it be it's own script that can be run when needed and someone can monitor it.

**Comment by forrest-rm** [comment]
Given that it will be hard to monitor the arms running at ProMat or during overnight longevity tests, I'll leave it as is for now, but we can monitor how the arm behaves over time.

**Pull request merged**
